### ISSUE TITLE
missing tikz logo

### ISSUE THREAD

**Issue by kexplorning** [ho-tex/hologo#1]
Hello, I happened to find that `tikz` logo is missing.

I have searched the manual, and tried `\hologo{tikz}`, but it seemed to be missing.

Is there any reason or something inconvenient to realize it?

**Comment by davidcarlisle** [comment]
I  suppose it could be added, although there are thousands of packages on ctan,  hologo can't promise to offer logos for them all... I think most people just write TikZ but I suppose you are looking for the italic k.

`/usr/local/texlive/2019/texmf-dist/doc/latex/tikz-dependency/pgfmanual-en-macros.tex`

Just uses

```
\def\pgfname{\textsc{pgf}}
\def\tikzname{Ti\emph{k}Z}
```

**Comment by kexplorning** [comment]
Many thanks for replying.
