### ISSUE TITLE
\section{\hologo{LaTeXe}} fails with hyperref

### ISSUE THREAD

**Issue by schtandard** [ho-tex/hologo#4]
The MWE
```latex
\documentclass{article}

\usepackage{hologo}
\usepackage{hyperref}

\begin{document}

\section{\hologo{LaTeXe}}

\end{document}
```
leads to the error
```
! Undefined control sequence.
<argument> \textepsilon 
```
with an up-to-date TeX Live 2020.

This seems to be a new behavior; at least I did not experience it about a year ago.

**Comment by u-fischer** [comment]
I need to think about this, for now load the greek definitions manually:

~~~~
\usepackage{hyperref}
\input{puenc-greekbasic.def}
~~~~

**Comment by u-fischer** [comment]
A new version with the fix has been uploaded to ctan.
