### ISSUE TITLE
Suggestion! Include new logos variants.

### ISSUE THREAD

**Issue by tuxkernel** [ho-tex/hologo#7]
![hologo2](https://user-images.githubusercontent.com/785911/202142248-47964d7e-7235-4aa0-8439-d5bdda8ea8d5.png)
Happy TeXing...

**Comment by davidcarlisle** [comment]
The package already provides pdfLaTeX. Admittedly it could perhaps have used small caps for pdf. However we can't easily change that now as it would change too many existing documents.

As the point of a "logo" is that the same formatting is used everywhere, I'm not keen on the idea of an alternative PDFTeX logo using a different logo for the same thing.

**Comment by u-fischer** [comment]
@davidcarlisle  

> As the point of a "logo" is that the same formatting is used everywhere

Tell that the pdftex manual maintainer ;-)

![image](https://user-images.githubusercontent.com/4047173/202147927-a22195e1-8db4-4714-a95c-8ccf84f914fa.png)


![image](https://user-images.githubusercontent.com/4047173/202148133-d995c256-a327-4507-bcff-6ef3ecb4a380.png)

![image](https://user-images.githubusercontent.com/4047173/202148234-52588929-1beb-47da-b7a2-be291a013aab.png)

![image](https://user-images.githubusercontent.com/4047173/202148402-7752e732-15e7-4f05-bb1e-90709881d814.png)

![image](https://user-images.githubusercontent.com/4047173/202148530-d0657674-0636-42fa-9a2f-ed2ab4bddf1a.png)

**Comment by josephwright** [comment]
> @davidcarlisle
> 
> > As the point of a "logo" is that the same formatting is used everywhere
> 
> Tell that the pdftex manual maintainer ;-)
> 
> ![image](https://user-images.githubusercontent.com/4047173/202147927-a22195e1-8db4-4714-a95c-8ccf84f914fa.png)
> 
> ![image](https://user-images.githubusercontent.com/4047173/202148133-d995c256-a327-4507-bcff-6ef3ecb4a380.png)
> 
> ![image](https://user-images.githubusercontent.com/4047173/202148234-52588929-1beb-47da-b7a2-be291a013aab.png)
> 
> ![image](https://user-images.githubusercontent.com/4047173/202148402-7752e732-15e7-4f05-bb1e-90709881d814.png)
> 
> ![image](https://user-images.githubusercontent.com/4047173/202148530-d0657674-0636-42fa-9a2f-ed2ab4bddf1a.png)

Nowadays that's ... probably @davidcarlisle  and me :)

**Comment by tuxkernel** [comment]
Houston, we have a problem! After all it was only one suggestion. Happy TeXing ;-)
